# Generated by Django 5.1.3 on 2024-11-29 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
