# Generated by Django 5.1.3 on 2024-11-29 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='farmer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
