# Generated by Django 5.1.3 on 2024-11-29 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_product_farmer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='farmer_name',
        ),
    ]
