# Generated by Django 5.1.3 on 2024-12-04 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_farmer_billinginfo_notification_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmer',
            old_name='name',
            new_name='username',
        ),
    ]
