# Generated by Django 5.1.3 on 2024-12-04 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_rename_name_farmer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='farmer',
            name='username',
        ),
        migrations.AddField(
            model_name='farmer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='market.product'),
        ),
    ]
