# Generated by Django 5.1.3 on 2024-12-04 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_alter_farmer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinginfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='billinginfo',
            name='farmer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='market.farmer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='farmer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='market.farmer'),
            preserve_default=False,
        ),
    ]
