# Generated by Django 5.1.3 on 2024-12-04 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_remove_billinginfo_user_remove_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
    ]
