# Generated by Django 5.1.3 on 2024-12-04 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_remove_order_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.DeleteModel(
            name='BillingInfo',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Farmer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
