# Generated by Django 5.1.3 on 2024-12-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0020_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
