# Generated by Django 5.1.3 on 2024-12-08 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_user_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
